jobs:
  - job: build_pwsh_win2016
    pool:
      vmImage: vs2017-win2016
    steps:
    - pwsh: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/out/testResults.xml'
        testRunTitle: 'pwsh_win2016'
      displayName: 'Publish Test Results'
    - pwsh: ./build -Tastk Publish
      displayName: 'Publish PowerShell Module'
      env:
        PSGALLERY_API_KEY: $(PSGALLERY_API_KEY)
